apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: PACKAGE_NAME-opsrc
  namespace: openshift-marketplace
spec:
  authorizationToken:
    secretName: PACKAGE_NAME-opsrctoken
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: QUAY_NAMESPACE